정상적인 흐름을 코딩하기도 버거운데 예외 상황까지 처리하는 것은 쉽지 않다. 그래서 예외와 관련된 코드는 자주 엉망이 되거나 무성의하게 만들어지기 쉬운데, 잘못된 예외 처리 코드 때문에 찾기 힘든 버그가 생길 수도 있고, 생각치 못했던 예외 상황이 발생했을 때 난처해질 수도 있다.

`JdbcTemplate` 을 대표로 하는 스프링의 데이터 액세스 기능에 담겨 있는 예외 처리와 관련된 접근 방법에 대해 알아보자.



### 4.1 사라진 SQLException

다음과 같은 코드를 **예외 블랙홀**이라고 한다.

``` java
try {
  ...
} catch (SQLException e) {
  // 예외를 잡고는 아무것도 하지 않는다.
}
```



위의 코드는 예외 발생을 무시하고 정상적인 상황인 것처럼 진행하겠다는 분명한 의도가 있는 것이 아니라면 절대 만들면 안 되는 코드이다. 예외가 발생했을 때 `catch` 블록으로 잡아내는 것까진 좋은데, 그러고 아무것도 하지 않으면 정말 위험하다. 프로그램 실행 중에 어디선가 오류가 있어서 예외가 발생했을텐데, 그것을 무시하고 계속 진행해버리기 때문이다. 결국 발생한 예외로 인해 어떤 기능이 비정상적으로 동작하거나, 메모리나 리소스가 소진될 수도 있다. 더욱 큰 문제는 그 오류나 이상한 결과의 원인이 무엇인지 찾아내기가 무척 힘들다는 점이다. 

추가로, 다음과 같은 단순 로그나 메시지 출력하는 코드도 마찬가지이다. **예외는 반드시 처리되어야 한다.**



``` java 
} catch (SQLException e) {
  System.out.println(e);
}
```



``` java
} catch (SQLException e) {
  e.printStackTrace();
}
```



예외를 처리할 때 반드시 지켜야 할 핵심 원칙은 한 가지이다. **모든 예외는 적절히 복구되든지, 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보되어야 한다.** 굳이 예외를 잡아서 조치를 취할 방법이 없다면 잡지 말고 메서드에 `throws SQLException` 을 선언해서 메서드 밖으로 던지고 자신을 호출한 코드에 예외 처리 책임을 전가하는 것이 좋다.



**무의미하고 무책임한 throws**도 좋지 않다. 가끔 JDK API나 라이브러리가 던지는 각종 예외들을 처리하는 코드를 `throws Exception` 으로 뭉뚱그려 처리하는 경우가 있다.



``` java
public void method1() throws Exception {
  method2();
  ...
}

public void method2() throws Exception {
  method3();
  ...
}

public void method3() throws Exception {
  ...
}
```

`throws Exception` 이 선언되어 있는 메서드에서는 의미있는 정보를 얻을 수 없다. 결국 이런 메서드를 사용하는 메서드에서 역시 `throwss Exception` 을 따라 붙이는 수밖에 없다. 결과적으로 적절한 처리를 통해 복구될 수 있는 예외 상황도 제대로 다룰 수 있는 기회를 박탈당하게 된다. 



그렇다면 예외를 어떻게 다루어야 할까? 가장 큰 이슈는 체크 예외`checked exception` 라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법이다. 이펙티브 자바에서 검사/비검사 예외라고 불렀던 것이다. 



자바에서 `throw`  를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.



- Error

`java.lang.Error` 클래스의 서브 클래스들이다. 비정상적인 상황이 발생했을 경우 사용된다. 그래서 주로 JVM에서 발생시키고, 애플리케이션 코드에서 잡으려고 하면 안된다. `OutOfMemoryError`나 `ThreadDeath` 같은 에러는 `catch` 블록으로 잡아봤자 아무런 대응 방법이 없다. 따라서 시스템 레벨에서 특별한 작업을 하는 것이 아니라면 애플리케이션에서는 이런 에러에 대한 처리는 신경쓰지 않아도 된다.



- Exception과 예외 처리

`java.lang.Exception` 클래스와 그 서브클래스로 정의되는 예외들은 에러와는 달리 개발자들이 만든 애플리케이션 코드의 작업 중에 예외 상황이 발생했을 경우 사용된다. `Exception` 클래스는 다시 checked Exception과 unchecked Exception으로 구분된다. 전자는 `Exception` 클래스의 서브 클래스이면서 `RuntimeException` 클래스를 상속하지 **않은** 것들이고, 후자는 `RuntimeException` 을 상속한 클래스들을 말한다.



![자바 예외 구분: Checked Exception, Unchecked Exception](https://madplay.github.io/img/post/2019-03-02-java-checked-unchecked-exceptions-1.png)



일반적으로 예외는 `Exception` 클래스의 서브 클래스 중에서 `RuntimeException` 을 상속하지 않은 것만을 말하는 체크 예외만이라고 생각해도 된다. 체크 예외가 발생할 수 있는 메서드를 사용하는 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다. 사용할 메서드가 체크 예외를 던진다면 이를 `catch` 블록으로 잡든지, 아니면 다시 `throws` 를 정의해서 메서드 밖으로 던져야 한다. 그렇지 않으면 컴파일 에러가 발생한다. 



- RuntimeException과 언체크/런타임 예외

`java.lang.RuntimeException` 클래스를 상속한 예외들은 명시적인 예외 처리를 강제하지 않기 때문에 언체크 예외`unchecked Exception` 이라고 한다. 에러와 마찬가지로 이 런타임 예외는 `catch` 블록으로 잡거나 `throws` 로 선언하지 않아도 된다. 물론 명시해줘도 된다.



런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이다. `NullPointerException` 이나 `IllegalArgumentException` 등이 있다. 이러한 예외는 코드에서 미리 조건을 체크하도록 만든다면 피할 수 있다. 즉, **피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 만든 것 런타임 예외**이다. 그렇기 때문에 런타임 예외는 예상치 못한 상황에서 발생하는 것이 아니기 때문에 굳이 `catch` 블록이나 `throws` 가 필수적이지 않다.



예외를 처리하는 방법에는 예외 복구, 예외처리 회피, 그리고 예외 전환이 있다.

먼저 예외 복구는 **예외 상황을 파악하고 문제를 해결해서 정상적인 상태로 돌려놓는 것**이다. 예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 유도해주는 것이다. 단, 에러 메시지를 사용자에게 그냥 보여주는 것은 예외 복구라고 볼 수 없다. 예외가 처리됐으면 애플리케이션에서는 정상적으로 설계된 흐름에 따라 진행되어야 하기 때문이다.

예외 처리 코드를 강제하는 체크 예외들은 이렇게 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다. API를 사용하는 개발자로 하여금 예외 상황이 발생할 수 있다는 것을 인식하도록 도와주고, 이에 대한 적절한 처리를 시도하도록 요구하는 것이다.



다음은 통제 불가능한 외부 요인으로 인해 예외가 발생하면 `MAX_RETRY` 만큼 재시도를 하는 코드이다.

``` java
int maxRetry = MAX_RETRY;

while (maxRetry-- > 0) {
  try {
    ...											// 예외가 발생할 가능성이 있는 시도
    return;									// 작업 성공
  } catch (SomeException e) {
    // 로그 출력. 정해진 시간만큼 대기
  } finally {
    // 리소스 반납. 정리 작업
  } 
}
throw new RetryFailedException();	// 최대 재시도 횟수를 넘기면 직접 예외 발생
```



두번째로 예외 처리 회피는 **예외 처리를 자신이 담당하지 않고, 자신을 호출한 쪽으로 던져버리는 것**이다. `throws` 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나, `catch` 문으로 예외를 잡고 로그를 남긴 후 다시 예외를 던지는 것이다. 예외 처리를 회피하려면 반드시 다른 오브젝트나 메서드가 예외를 대신 처리할 수 있도록 던져주어야 한다.



예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다. 콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외 처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 것이 최선의 방법이라는 확신이 있어야 한다



마지막으로 예외 전환은 **예외를 복구해서 정상적인 상태로 만들 수 없을 때 예외를 메서드 밖으로 던지는 것**이다. 예외 회피와 비슷하지만 발생한 예외를 그대로 넘기는 것이 아니라, **적절한 예외로 전환**해서 던진다. 예외 전환은 보통 두 가지 목적으로 사용된다.

첫째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외 상황에 대한 적절한 의미를 부여하지 못하는 경우에, 의미를 분명히 해줄 수 있는 예외로 바꿔 주는 것이다. 기술적인 로우 레벨을 상황에 적합한 의미를 가진 예외로 변경하는 것이다. 보통 전환하는 예외에 원래 발생한 예외를 담아서 **중첩 예외**로 만드는 것이 좋다. 중첩 예외는 생성자나 `initCause()` 메서드로 근본 원인이 되는 예외를 넣어주면 된다.



두 번째 전환 방법은 예외를 처리하기 쉽고 단순하게 만들기 위해 **포장**하는 것이다. 이 방법은 중첩 예외를 이용하는 방식은 같지만 의미를 명확하게 하려고 다른 예외로 전환하는 것이 아니다. **주로 예외 처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우**에 사용한다. 일반적으로 체크 예외를 계속 `throws` 를 사용해서 넘기는 것은 메서드 선언만 지저분해지고 아무 장점이 없다. 어차피 복구 불가능한 예외라면 가능한 한 빨리 런타임 예외로 포장해서 다른 계층의 메서드에 불필요한 `throws` 선언이 들어가지 않도록 해주어야 한다.



### 4.2 예외 전환

스프링의 `JdbcTemplate` 은 예외 전환 방식을 채택했다. `DataAccessException` 은 일단 런타임 예외로 `SQLException` 을 포장해주는 역할을 한다. 그렇게 해서 대부분 복구가 불가능한 예외인 `SQLException` 을 애플리케이션 레벨에서 신경 쓰지 않도록 해주는 것이다. 
